### ISSUE TITLE
Could not load file ...

### ISSUE THREAD

**Issue by mrmartineau** [MaciekBaron/sublime-list-stylesheet-vars#1]
Hi Maciek, thanks for your amazingly fast work on this - it is great!

My first attempt testing the plugin was with SCSS, it did not go as expected. I have `kickoff.scss` that imports a bunch of other `scss` files for the current project. When using the shortcut, I get these errors:

```
command: list_stylesheet_variables
Could not load file /variables
Could not load file /mixins
Could not load file /normalize
Could not load file /choreographic-grid
Could not load file /grid-static
Could not load file /typography
Could not load file /forms
Could not load file /tables
Could not load file /code
Could not load file /components
Could not load file /sprites
Could not load file /buttons
Could not load file /button-groups
Could not load file /carousel
Could not load file /app
Could not load file /blog
Could not load file /portfolio-colours
Could not load file /utilities
Could not load file /responsive-utilities
Could not load file /print
```

All the errors are files that the plugin could not find. I'm not sure if you're aware but `SASS` imports are slightly different to `LESS`. Sass filesname can have an underscore at the beginning so that they do not compile directly, this means that your plugin might not be 'looking' for the right file, as they may have an underscore in the name. Have a look at the [SASS docs](http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#partials) to see what I mean.

---

With the default plugin settings, the plugin works flawlessly when viewing my `_variables.scss` file however it does not recognise any other vars from other files. 

I haven't tried with Stylus yet, but will give it a go now.

Thanks again mate - amazing work!

**Comment by MaciekBaron** [comment]
Hi mate, thanks for testing the code.

I wasn't aware of partials, so I've added support for them. I've done a quick test and I think it works.

I've also added support for [index styles](http://learnboost.github.io/stylus/docs/import.html) for Stylus as this language also apparently handles certain imports differently.

**Comment by mrmartineau** [comment]
Thanks it works great now, but is there a way to get vars if I'm in a partial file that is being imported from another, i.e. there are no `@import` rule in the file and no variable defined in that file?

**Example:**

```
|- kickoff.scss
|-- _vars.scss
|-- _typography.scss
```

`kickoff.scss` imports both `_vars.scss` and `_typography.scss`. `_typography.scss` uses vars from `_vars.scss` but has no way to access these variables, with your plugin, that I can see. Could the plugin look at the directory that the file is in and then look for vars that have been assigned? I expect that would be a rather difficult task, especially if there are multiple nested folders like I have on a current project.

Index styles look like Sass' partials..

**Comment by MaciekBaron** [comment]
Would it help if I've added another setting in the settings file to search through files of the same type in the same directory?

**Comment by mrmartineau** [comment]
Yes, I think that would be a perfect solution to the problem. Would you be able to make it search through sub-folders as well?
