### ISSUE TITLE
How to install this in Sublime Text 3?

### ISSUE THREAD

**Issue by the-glima** [MaciekBaron/sublime-list-stylesheet-vars#11]
I've cloned this repo to my package folder but doesn't work.

**Comment by the-glima** [comment]
Forget it.

I've missed the configurations settings to make it work.

**Comment by MaciekBaron** [comment]
This package is available in Sublime Package Control, and that's the easiest way to install it.

**Comment by kisonay** [comment]
This is no longer showing in package control. From what I can see, it is only listed as ST2 on https://sublime.wbond.net

**Comment by mrmartineau** [comment]
It still does not appear in Package Control for ST3.. any reason why this is?

**Comment by MaciekBaron** [comment]
Package Control has changed the way ST3-compatible plugins are added to the list, I still haven't gotten around to updating it. I'll do that soon.

**Comment by mrmartineau** [comment]
Anything we can help with?

**Comment by mrmartineau** [comment]
Should this line be removed to fix it? https://github.com/wbond/package_control_channel/blob/master/repository/l.json#L474

**Comment by MaciekBaron** [comment]
Yep I'm doing that now.

**Comment by MaciekBaron** [comment]
I've updated the conf files in the package control channel repo.

**Comment by mrmartineau** [comment]
Thanks, now we wait for Will to merge it...

**Comment by MaciekBaron** [comment]
They've merged now, you should be able to install the plugin now.
