### ISSUE TITLE
problem with other plugins

### ISSUE THREAD

**Issue by ghost** [MaciekBaron/sublime-list-stylesheet-vars#13]
Does not work with plugins color highlighter, bracket highlighter and trailing spaces...

**Comment by MaciekBaron** [comment]
Hi DuKab, I don't use these plugins. Could you please elaborate? Are the hotkeys clashing?

**Comment by ghost** [comment]
Hi, hotkeys work, but when i select variable from the list it doesn't show in the file, doesn't write in file...

**Comment by MaciekBaron** [comment]
To be honest I'm inserting text in a standard way so I'm not sure what could be changed to make it work in your particular case.

**Comment by ghost** [comment]
ok, i will disable these plugins because i like to work with sass:)
