### ISSUE TITLE
doesn't work with additional .erb extension

### ISSUE THREAD

**Issue by dannyatFINE** [MaciekBaron/sublime-list-stylesheet-vars#14]
requesting support for `.scss.erb` and `.sass.erb` extentions

**Comment by MaciekBaron** [comment]
Hi Danny,

Is there a resource outlining the syntactical differences between SASS files and their ERB equivalents?

A quick google suggested that you can define variables like this:

```
$my_image: <%= asset_path 'blah.png' %>
```

I assume this is a pre-pre-processor :) (Sorry, haven't used this combination before)

**Comment by dannyatFINE** [comment]
the erb extension is added if you plan to precompile erb into your stylesheets in the same way you would with your markup. 

A common use case would be something similar to what your found in your research. Here is an example:

```
$assets_directory: <%= "#{asset_base_path}" %>;
$header_background_color: url(#{$assets_directory}/ui/promo-background.png) repeat #383221;
```

I don't think its really common, but at the same time, it isn't uncommon either.

**Comment by MaciekBaron** [comment]
Thanks Danny!

In that case the value displayed for `$assets_directory` would be `"#{asset_base_path}"` (text in between the `<%=` tags) and for `$header_background_color` the whole thing (`url(#{$assets_directory}/ui/promo-background.png) repeat #383221`)

Does that sound right?

**Comment by dannyatFINE** [comment]
Yes sir

**Comment by MaciekBaron** [comment]
I've added support for those files, a quick test with your example showed it working, let me know if there are any issues.
