### ISSUE TITLE
Add paste / translate support

### ISSUE THREAD

**Issue by LeonardDrs** [MaciekBaron/sublime-list-stylesheet-vars#16]
Hi,

Thanks for your plugin !

Having a support for translating a pasted value into its variable name would be delightful.

eg:
Having those variables

```
$white-color: #fff;
$black-color: #000;
$brand-color: #ff6600;
```

Whenever I paste `ff6600`, ST translate `ff6600` into `$brand-color`

Or we could find a variable by typing its value in the <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>L</kbd> panel.

Little plus:
We could also look for a variable into the current project, not just into the current opened files.

**Comment by MaciekBaron** [comment]
What if the value is shared by multiple variables? The plugin would have to display a list of all possible variables.

I guess this could be implemented but it is a peculiar use-case.

**Comment by LeonardDrs** [comment]
Oh my, closing this issue as I totally forgot about it.
