### ISSUE TITLE
SCSS - "readImported": false, "readAllViews": true  - error

### ISSUE THREAD

**Issue by mrmartineau** [MaciekBaron/sublime-list-stylesheet-vars#2]
With these settings:

``` json
"readImported": false,
"readAllViews": true
```

I get this error in the Sublime console:

```
command: list_stylesheet_variables
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./stylevariables.py", line 72, in run
```

The vars do not get listed/no output is seen.

**Comment by MaciekBaron** [comment]
Hmm, interesting, I've just tested it and it worked.

This `./sublime_plugin.py` file that appears in your log, what is it? Perhaps that's the culprit here.

**Comment by mrmartineau** [comment]
I have no idea what it is.. It is referenced on the first line of `stylevariables.py` 

``` py
import sublime, sublime_plugin, os, re
```

**Comment by MaciekBaron** [comment]
Ah, well that's the main plugin library, for a second I thought it might be some test plugin that you were working on... I can't reproduce this problem but I'll look into it.

**Comment by mrmartineau** [comment]
FYI I just fixed this in my pull request
