### ISSUE TITLE
Stylus problems

### ISSUE THREAD

**Issue by mrmartineau** [MaciekBaron/sublime-list-stylesheet-vars#3]
I don't normally use Stylus so I downloaded a boilerplate from https://github.com/neojp/stylus-boilerplate. It seems that because Stylus does not use an `@` or `$` before it's vars, it is much more difficult to determine if the result is a variable or not. Stylus uses a single equals `=` for assignment and for conditionals. 

See my screen grabs below as an example:
![](http://cl.ly/PMlX/Screen%20Shot%202013-06-02%20at%2016.27.39.png)
![](http://cl.ly/PLzP/Screen%20Shot%202013-06-02%20at%2016.27.51.png)
![](http://cl.ly/PLys/Screen%20Shot%202013-06-02%20at%2016.32.09.png)

Is there a way to regex the first characters on a line so that if a conditional is detected, starting at column 8, it will be ignored?

**Comment by MaciekBaron** [comment]
I've improved the regex for stylus, it should now be better however it's difficult or perhaps even impossible to determine whether a variable in Stylus is a helper variable or something useful. Will need to have a think.

**Comment by mrmartineau** [comment]
I agree, getting Stylus to work effectively would be a pretty tall order. I think what you have now is suffiecient, however, I did find one more issue that I hadn't seen before. If a CSS rule has `input[type=submit], your regex thinks its a variable.. see below:

![](http://cl.ly/PMNi/Screen%20Shot%202013-06-02%20at%2018.12.43.png)

**Comment by MaciekBaron** [comment]
Thanks, I've pushed a small change to the repo which should fix this.

**Comment by mrmartineau** [comment]
Yes! that seems to work perfectly.
