### ISSUE TITLE
Add this to Package Control?

### ISSUE THREAD

**Issue by mrmartineau** [MaciekBaron/sublime-list-stylesheet-vars#7]
Do you think its ready to add to Package Control? I think it is ready. We could post about the plugin on the Sublime forum/Twitter to give a bit more of a test beforehand. What do you think?

**Comment by MaciekBaron** [comment]
I'll just polish the Stylus regex and add it to PC tomorrow. Will let you know.

**Comment by MaciekBaron** [comment]
It's finally in Package Control :)
